version: 2
jobs:
  build:
    docker:
      - image: 'circleci/node:lts'
    steps:
      - checkout
      - restore_cache:
          keys:
            - 'v1-dependencies-{{ checksum "package.json" }}'
            - v1-dependencies-
      - run: 'npm install lint && npm update && npm install'
      - save_cache:
          paths:
            - node_modules
          key: 'v1-dependencies-{{ checksum "package.json" }}'
  test:
    docker:
      - image: 'circleci/node:lts'
    steps:
      - run: 'npm lint'
workflows:
  version: 2
  build-test:
    jobs:
      - build
      - test:
          requires:
          - build
